services:
  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Tu configuración Nginx
      - ./index.html:/usr/share/nginx/html/index.html  # Montar el archivo HTML
    networks:
      - ag

networks:
  ag:
    external: true
